version: '3.4'

services:

  mecor.api:
    image: ${DOCKER_REGISTRY-}mecorapi
    build:
      context: .
      dockerfile: Mecor.Api/Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mecor
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019
